#!/usr/bin/env python3
"""Plan an external corpus import without copying or mutating images.

Inputs are the read-only audit JSON and complete inventory JSON generated by
`scripts/audit_external_corpus.py --inventory-output ...`.

Outputs are review artifacts only:
- class_mapping_proposal.csv
- unmapped_extras.csv
- duplicate_conflicts.csv
- weak_classes.csv
- import_manifest.preview.json
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import sys
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

IMAGE_EXTENSIONS = {".bmp", ".jpg", ".jpeg", ".png", ".webp", ".tif", ".tiff"}
PLAN_SCHEMA_VERSION = "external-corpus-import-plan.v1"
DEFAULT_SOURCE_PRIORITY = (
    "Clinic-Codex__data__Elements",
    "AI_clinic_class__MainElem_Original",
    "AI_clinic_class__Main_Elements",
)
VALID_STATUSES = {
    "selected",
    "duplicate_same_class",
    "conflict_cross_class",
    "conflict_mapped_unmapped",
    "suspected_reencode",
    "unmapped_extra",
    "invalid_empty_file",
    "invalid_unreadable_image",
}


@dataclass(frozen=True)
class PlannedImage:
    source: str
    class_dir: str
    normalized_name: str
    matched_active_class: str | None
    path: str
    extension: str
    size_bytes: int
    sha256_bytes: str | None
    sha256_pixels: str | None
    warnings: list[str]
    status: str
    status_reason: str


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(chunk_size), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def canonical_json_sha(value: Any) -> str:
    return sha256_text(json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")))


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def csv_cell(value: Any) -> Any:
    if value is None:
        return ""
    if isinstance(value, (int, float)):
        return value
    text = str(value)
    text = text.replace("\x00", "")
    if text.startswith(("=", "+", "-", "@", "\t", "\r", "\n")):
        return "'" + text
    return text


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({name: csv_cell(row.get(name, "")) for name in fieldnames})


def deterministic_split_counts(count: int, val_fraction: float) -> tuple[int, int]:
    if count <= 0:
        return 0, 0
    n_val = max(1, int(count * val_fraction))
    n_val = min(n_val, count - 1)
    return count - n_val, n_val


def validate_duplicate_groups_not_truncated(audit: dict[str, Any]) -> None:
    for group_key in ("duplicate_groups", "pixel_duplicate_groups"):
        for group in audit.get(group_key, []):
            entries = group.get("entries", [])
            if group.get("count") != len(entries):
                raise ValueError(f"{group_key} contains truncated group: count={group.get('count')} entries={len(entries)}")


def validate_inventory(audit: dict[str, Any], inventory: dict[str, Any]) -> list[dict[str, Any]]:
    images = inventory.get("images")
    if not isinstance(images, list):
        raise ValueError("inventory JSON must contain an images list")
    if audit.get("inventory_count") != len(images):
        raise ValueError(f"inventory_count mismatch: audit={audit.get('inventory_count')} inventory={len(images)}")
    audit_run_id = audit.get("audit_run_id")
    inventory_run_id = inventory.get("audit_run_id")
    if audit_run_id and inventory_run_id and audit_run_id != inventory_run_id:
        raise ValueError(f"audit/inventory run mismatch: audit={audit_run_id} inventory={inventory_run_id}")
    by_source = Counter(img["source"] for img in images)
    audit_by_source = {source["name"]: source["image_count"] for source in audit.get("sources", [])}
    if dict(sorted(by_source.items())) != dict(sorted(audit_by_source.items())):
        raise ValueError(f"source image counts mismatch: audit={audit_by_source} inventory={dict(by_source)}")
    return images


def validate_config(audit: dict[str, Any], active_config: Path) -> None:
    current = sha256_file(active_config)
    expected = audit.get("active_config_sha256")
    if expected and current != expected:
        raise ValueError(f"active config changed since audit: expected={expected} current={current}")


def iter_source_images_like_audit(source_root: Path):
    if not source_root.exists() or not source_root.is_dir():
        raise ValueError(f"source missing or not directory: {source_root}")
    for class_dir in sorted([path for path in source_root.iterdir() if path.is_dir()], key=lambda path: path.name):
        for child in sorted(class_dir.iterdir()):
            if child.is_file() and child.suffix.lower() in IMAGE_EXTENSIONS:
                yield child


def validate_source_freshness(audit: dict[str, Any], images: list[dict[str, Any]]) -> None:
    expected = Counter((img["source"], img["source_path"]) for img in images)
    actual: Counter[tuple[str, str]] = Counter()
    for source, source_path in sorted(expected):
        root = Path(source_path)
        actual[(source, source_path)] = sum(1 for _ in iter_source_images_like_audit(root))
    if actual != expected:
        raise ValueError(f"source image counts changed since audit: expected={dict(expected)} actual={dict(actual)}")

    for image in images:
        path = Path(image["path"])
        if not path.exists() or not path.is_file():
            raise ValueError(f"inventoried image missing: {path}")
        current_size = path.stat().st_size
        if current_size != image.get("size_bytes"):
            raise ValueError(f"inventoried image size changed: {path}")
        expected_hash = image.get("sha256_bytes")
        if expected_hash and current_size > 0 and sha256_file(path) != expected_hash:
            raise ValueError(f"inventoried image bytes changed: {path}")


def sort_key_for_image(image: dict[str, Any], source_rank: dict[str, int]) -> tuple[int, str, str, str]:
    return (
        source_rank.get(image["source"], 10_000),
        image.get("matched_active_class") or "",
        image["class_dir"],
        image["path"],
    )


def plan_images(images: list[dict[str, Any]], source_priority: list[str]) -> list[PlannedImage]:
    source_rank = {name: idx for idx, name in enumerate(source_priority)}
    conflict_paths: set[str] = set()
    mapped_unmapped_duplicate_paths: set[str] = set()
    duplicate_unmapped_paths: set[str] = set()
    for digest_key in ("sha256_bytes", "sha256_pixels"):
        grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
        for image in images:
            if image.get("size_bytes", 0) <= 0:
                continue
            digest = image.get(digest_key)
            if digest:
                grouped[digest].append(image)
        for entries in grouped.values():
            if len(entries) <= 1:
                continue
            classes = {entry.get("matched_active_class") for entry in entries if entry.get("matched_active_class")}
            has_unmapped = any(not entry.get("matched_active_class") for entry in entries)
            if len(classes) > 1:
                conflict_paths.update(entry["path"] for entry in entries if entry.get("matched_active_class"))
            if classes and has_unmapped:
                mapped_unmapped_duplicate_paths.update(entry["path"] for entry in entries)
            if not classes and has_unmapped:
                duplicate_unmapped_paths.update(entry["path"] for entry in entries)

    duplicate_status: dict[str, tuple[str, str]] = {}
    for digest_key in ("sha256_bytes", "sha256_pixels"):
        grouped_key_to_entries: dict[tuple[str, str], list[dict[str, Any]]] = defaultdict(list)
        for image in images:
            if image["path"] in conflict_paths or image["path"] in mapped_unmapped_duplicate_paths:
                continue
            if image.get("size_bytes", 0) <= 0 or not image.get("matched_active_class"):
                continue
            digest = image.get(digest_key)
            if digest:
                grouped_key_to_entries[(image["matched_active_class"], digest)].append(image)

        for (_class_name, _digest), entries in sorted(grouped_key_to_entries.items()):
            if len(entries) <= 1:
                continue
            ordered = sorted(entries, key=lambda item: sort_key_for_image(item, source_rank))
            primary = ordered[0]
            for duplicate in ordered[1:]:
                if duplicate["path"] in duplicate_status:
                    continue
                if duplicate.get("sha256_bytes") and duplicate.get("sha256_bytes") == primary.get("sha256_bytes"):
                    duplicate_status[duplicate["path"]] = ("duplicate_same_class", f"same_byte_or_pixel_as:{primary['path']}")
                else:
                    duplicate_status[duplicate["path"]] = ("suspected_reencode", f"same_pixels_as:{primary['path']}")

    planned: list[PlannedImage] = []
    for image in sorted(images, key=lambda item: sort_key_for_image(item, source_rank)):
        path = image["path"]
        warnings = list(image.get("warnings") or [])
        if image.get("size_bytes", 0) <= 0:
            status, reason = "invalid_empty_file", "empty_file_excluded"
        elif any(str(warning).startswith(("pixel_hash_failed", "pillow_unavailable")) for warning in warnings) or image.get("sha256_pixels") is None:
            status, reason = "invalid_unreadable_image", "pixel_hash_missing_or_failed"
        elif path in conflict_paths:
            status, reason = "conflict_cross_class", "duplicate_hash_maps_to_multiple_active_classes"
        elif path in mapped_unmapped_duplicate_paths:
            status, reason = "conflict_mapped_unmapped", "duplicate_hash_maps_to_active_and_unmapped_sources"
        elif not image.get("matched_active_class"):
            status, reason = "unmapped_extra", "source_class_not_in_active_taxonomy"
            if path in duplicate_unmapped_paths:
                reason += ";duplicate_unmapped_pending_review"
        elif path in duplicate_status:
            status, reason = duplicate_status[path]
        else:
            status, reason = "selected", "primary_unique_or_no_duplicate"
        planned.append(
            PlannedImage(
                source=image["source"],
                class_dir=image["class_dir"],
                normalized_name=image["normalized_name"],
                matched_active_class=image.get("matched_active_class"),
                path=path,
                extension=image["extension"],
                size_bytes=image["size_bytes"],
                sha256_bytes=image.get("sha256_bytes"),
                sha256_pixels=image.get("sha256_pixels"),
                warnings=warnings,
                status=status,
                status_reason=reason,
            )
        )
    status_count = Counter(item.status for item in planned)
    if sum(status_count.values()) != len(images):
        raise AssertionError("status closure invariant failed")
    unknown = set(status_count) - VALID_STATUSES
    if unknown:
        raise AssertionError(f"unknown statuses generated: {unknown}")
    return planned

def build_mapping_rows(audit: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for source in audit.get("sources", []):
        for item in source.get("classes", []):
            active = item.get("matched_active_class")
            rows.append(
                {
                    "source_dataset": source["name"],
                    "source_path": source["path"],
                    "source_folder": item["class_dir"],
                    "normalized_name": item["normalized_name"],
                    "match_status": item["match_status"],
                    "active_class_name": active or "",
                    "image_count": item["image_count"],
                    "decision": "map_to_active" if active else "quarantine",
                    "reviewer": "",
                    "notes": "",
                }
            )
    return sorted(rows, key=lambda row: (row["source_dataset"], row["source_folder"]))


def build_weak_rows(planned: list[PlannedImage], *, k_shot: int, q_queries: int, min_images_per_class: int, val_fraction: float) -> list[dict[str, Any]]:
    raw = Counter(item.matched_active_class for item in planned if item.matched_active_class)
    unique = Counter(item.matched_active_class for item in planned if item.status == "selected" and item.matched_active_class)
    rows: list[dict[str, Any]] = []
    min_episode = k_shot + q_queries
    for class_name in sorted(raw):
        raw_count = raw[class_name]
        unique_count = unique[class_name]
        train_count, val_count = deterministic_split_counts(unique_count, val_fraction)
        reasons: list[str] = []
        if unique_count < min_images_per_class:
            reasons.append("unique_below_min_images_per_class")
        if unique_count < min_episode:
            reasons.append("unique_below_k_shot_plus_q_queries")
        if train_count < k_shot:
            reasons.append("train_split_below_k_shot")
        if val_count < 1:
            reasons.append("val_split_empty")
        if reasons:
            rows.append(
                {
                    "class_name": class_name,
                    "raw_count": raw_count,
                    "unique_count": unique_count,
                    "train_count": train_count,
                    "val_count": val_count,
                    "decision": "needs_policy",
                    "reasons": ";".join(reasons),
                    "reviewer": "",
                    "notes": "",
                }
            )
    return rows


def build_conflict_rows(planned: list[PlannedImage]) -> list[dict[str, Any]]:
    return [
        {
            "status": item.status,
            "status_reason": item.status_reason,
            "sha256_bytes": item.sha256_bytes or "",
            "sha256_pixels": item.sha256_pixels or "",
            "source_dataset": item.source,
            "source_folder": item.class_dir,
            "active_class_name": item.matched_active_class or "",
            "path": item.path,
            "decision": "quarantine_all",
            "reviewer": "",
            "notes": "",
        }
        for item in planned
        if item.status in {"conflict_cross_class", "conflict_mapped_unmapped"}
    ]


def build_unmapped_rows(mapping_rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [
        {
            "source_dataset": row["source_dataset"],
            "source_folder": row["source_folder"],
            "normalized_name": row["normalized_name"],
            "image_count": row["image_count"],
            "decision": "quarantine",
            "reviewer": "",
            "notes": "",
        }
        for row in mapping_rows
        if not row["active_class_name"]
    ]


def write_plan_outputs(
    output_dir: Path,
    *,
    planned: list[PlannedImage],
    mapping_rows: list[dict[str, Any]],
    weak_rows: list[dict[str, Any]],
    conflict_rows: list[dict[str, Any]],
    unmapped_rows: list[dict[str, Any]],
    manifest: dict[str, Any],
    force: bool,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    outputs = [
        output_dir / "class_mapping_proposal.csv",
        output_dir / "unmapped_extras.csv",
        output_dir / "duplicate_conflicts.csv",
        output_dir / "weak_classes.csv",
        output_dir / "import_manifest.preview.json",
    ]
    if not force:
        existing = [path for path in outputs if path.exists()]
        if existing:
            raise FileExistsError(f"output files already exist; pass --force to overwrite: {existing}")

    write_csv(output_dir / "class_mapping_proposal.csv", ["source_dataset", "source_path", "source_folder", "normalized_name", "match_status", "active_class_name", "image_count", "decision", "reviewer", "notes"], mapping_rows)
    write_csv(output_dir / "unmapped_extras.csv", ["source_dataset", "source_folder", "normalized_name", "image_count", "decision", "reviewer", "notes"], unmapped_rows)
    write_csv(output_dir / "duplicate_conflicts.csv", ["status", "status_reason", "sha256_bytes", "sha256_pixels", "source_dataset", "source_folder", "active_class_name", "path", "decision", "reviewer", "notes"], conflict_rows)
    write_csv(output_dir / "weak_classes.csv", ["class_name", "raw_count", "unique_count", "train_count", "val_count", "decision", "reasons", "reviewer", "notes"], weak_rows)
    (output_dir / "import_manifest.preview.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def build_manifest(args: argparse.Namespace, audit_path: Path, inventory_path: Path, active_config: Path, audit: dict[str, Any], planned: list[PlannedImage], mapping_rows: list[dict[str, Any]], weak_rows: list[dict[str, Any]], conflict_rows: list[dict[str, Any]], unmapped_rows: list[dict[str, Any]]) -> dict[str, Any]:
    status_counts = Counter(item.status for item in planned)
    source_status_counts: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    class_counts: dict[str, dict[str, int]] = defaultdict(lambda: {"raw_count": 0, "selected_count": 0})
    for item in planned:
        source_status_counts[item.source][item.status] += 1
        if item.matched_active_class:
            class_counts[item.matched_active_class]["raw_count"] += 1
            if item.status == "selected":
                class_counts[item.matched_active_class]["selected_count"] += 1
    mapping_hash = canonical_json_sha(mapping_rows)
    audit_preflight = audit.get("preflight") or {}
    audit_preflight_blocking_reasons = list(audit_preflight.get("blocking_reasons") or [])
    return {
        "schema_version": PLAN_SCHEMA_VERSION,
        "audit_json": str(audit_path),
        "audit_json_sha256": sha256_file(audit_path),
        "inventory_json": str(inventory_path),
        "inventory_json_sha256": sha256_file(inventory_path),
        "active_config": str(active_config),
        "active_config_sha256": sha256_file(active_config),
        "audit_active_config_sha256": audit.get("active_config_sha256"),
        "active_class_count": audit.get("active_class_count"),
        "arguments": {
            "k_shot": args.k_shot,
            "q_queries": args.q_queries,
            "min_images_per_class": args.min_images_per_class,
            "val_fraction": args.val_fraction,
            "source_priority": args.source_priority,
            "allow_stale": args.allow_stale,
        },
        "mapping_hash": mapping_hash,
        "promotable": False,
        "low_count_policy": "unresolved",
        "image_count": len(planned),
        "status_counts": dict(sorted(status_counts.items())),
        "source_status_counts": {source: dict(sorted(counts.items())) for source, counts in sorted(source_status_counts.items())},
        "class_counts": dict(sorted(class_counts.items())),
        "weak_class_count": len(weak_rows),
        "conflict_image_count": len(conflict_rows),
        "mapped_unmapped_conflict_image_count": status_counts.get("conflict_mapped_unmapped", 0),
        "unmapped_class_count": len(unmapped_rows),
        "audit_preflight_pass": audit_preflight.get("status") == "pass" if "status" in audit_preflight else not audit_preflight_blocking_reasons,
        "audit_preflight_blocking_reasons": audit_preflight_blocking_reasons,
        "blockers": [
            *([f"audit_preflight:{reason}" for reason in audit_preflight_blocking_reasons]),
            *([f"conflict_cross_class_images:{len(conflict_rows)}"] if conflict_rows else []),
            *([f"conflict_mapped_unmapped_images:{status_counts.get('conflict_mapped_unmapped', 0)}"] if status_counts.get("conflict_mapped_unmapped", 0) else []),
            *([f"unmapped_extra_classes:{len(unmapped_rows)}"] if unmapped_rows else []),
            *([f"invalid_empty_files:{status_counts.get('invalid_empty_file', 0)}"] if status_counts.get("invalid_empty_file", 0) else []),
            *([f"invalid_unreadable_images:{status_counts.get('invalid_unreadable_image', 0)}"] if status_counts.get("invalid_unreadable_image", 0) else []),
            *([f"weak_classes:{len(weak_rows)}"] if weak_rows else []),
        ],
        "images": [asdict(item) for item in planned],
    }


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--audit-json", required=True)
    parser.add_argument("--inventory-json", required=True)
    parser.add_argument("--active-config", default="backend/codex_model/config.json")
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--k-shot", type=int, default=3)
    parser.add_argument("--q-queries", type=int, default=5)
    parser.add_argument("--min-images-per-class", type=int, default=2)
    parser.add_argument("--val-fraction", type=float, default=0.15)
    parser.add_argument("--source-priority", default=",".join(DEFAULT_SOURCE_PRIORITY), help="Comma-separated source priority for selecting duplicate primaries")
    parser.add_argument("--allow-stale", action="store_true", help="Do not rescan source counts/config for freshness")
    parser.add_argument("--force", action="store_true", help="Overwrite existing machine-generated preview outputs")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv if argv is not None else sys.argv[1:])
    audit_path = Path(args.audit_json).expanduser()
    inventory_path = Path(args.inventory_json).expanduser()
    active_config = Path(args.active_config).expanduser()
    output_dir = Path(args.output_dir).expanduser()

    try:
        audit = load_json(audit_path)
        inventory = load_json(inventory_path)
        validate_duplicate_groups_not_truncated(audit)
        images = validate_inventory(audit, inventory)
        if not args.allow_stale:
            validate_config(audit, active_config)
            validate_source_freshness(audit, images)
        source_priority = [item.strip() for item in args.source_priority.split(",") if item.strip()]
        planned = plan_images(images, source_priority)
        if len(planned) != len(images):
            raise AssertionError("planned image count mismatch")
        mapping_rows = build_mapping_rows(audit)
        unmapped_rows = build_unmapped_rows(mapping_rows)
        weak_rows = build_weak_rows(planned, k_shot=args.k_shot, q_queries=args.q_queries, min_images_per_class=args.min_images_per_class, val_fraction=args.val_fraction)
        conflict_rows = build_conflict_rows(planned)
        manifest = build_manifest(args, audit_path, inventory_path, active_config, audit, planned, mapping_rows, weak_rows, conflict_rows, unmapped_rows)
        write_plan_outputs(output_dir, planned=planned, mapping_rows=mapping_rows, weak_rows=weak_rows, conflict_rows=conflict_rows, unmapped_rows=unmapped_rows, manifest=manifest, force=args.force)
    except (OSError, ValueError, AssertionError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    print(json.dumps({
        "output_dir": str(output_dir),
        "image_count": len(planned),
        "status_counts": manifest["status_counts"],
        "blockers": manifest["blockers"],
    }, ensure_ascii=False, indent=2, sort_keys=True))
    return 1 if manifest["blockers"] else 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
